### ISSUE TITLE
404 Not Found [IP: 3.121.249.232 443]

### ISSUE THREAD

**Issue by tscpp** [tetratelabs/getenvoy-package#101]
**Describe the bug**
I try to install enovy using getenvoy as described here: https://www.getenvoy.io/install/. After i run `sudo add-apt-repository "deb [arch=amd64] https://dl.bintray.com/tetrate/getenvoy-deb $(lsb_release -cs) stable`. I also tried nightly, but it didn't work. My source.list is default except for getenvoy.

```
elias@ELIAS-LX:~$ sudo add-apt-repository \
> "deb [arch=amd64] https://dl.bintray.com/tetrate/getenvoy-deb \
> $(lsb_release -cs) \
> stable"
Repository: 'deb [arch=amd64] https://dl.bintray.com/tetrate/getenvoy-deb groovy stable'
Description:
Archive for codename: groovy components: stable
More info: https://dl.bintray.com/tetrate/getenvoy-deb
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Adding deb entry to /etc/apt/sources.list.d/archive_uri-https_dl_bintray_com_tetrate_getenvoy-deb-groovy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/archive_uri-https_dl_bintray_com_tetrate_getenvoy-deb-groovy.list
Hit:1 http://se.archive.ubuntu.com/ubuntu groovy InRelease
Get:2 http://se.archive.ubuntu.com/ubuntu groovy-updates InRelease [115 kB]    
Get:3 http://se.archive.ubuntu.com/ubuntu groovy-backports InRelease [101 kB]  
Ign:4 https://dl.bintray.com/tetrate/getenvoy-deb groovy InRelease             
Err:5 https://dl.bintray.com/tetrate/getenvoy-deb groovy Release
  404  Not Found [IP: 3.121.249.232 443]
Get:6 http://security.ubuntu.com/ubuntu groovy-security InRelease [110 kB]
Reading package lists... Done       
E: The repository 'https://dl.bintray.com/tetrate/getenvoy-deb groovy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
elias@ELIAS-LX:~$ 

```

**To Reproduce**

1. Update apt index.
    
    ```bash
    $ sudo apt-get update
    ```

2. Install packages required for apt to communicate via HTTPS.
    
    ```bash
    $ sudo apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common
    ```

3. Add the Tetrate GPG key.
    
    ```bash
    $ curl -sL 'https://getenvoy.io/gpg' | sudo apt-key add -
    ````

4. Verify the key has the fingerprint 5270 CEAC 57F6 3EBD 9EA9 005D 0253 D0B2 6FF9 74DB.
    
    ```bash
    $ apt-key fingerprint 6FF974DB
    ```

    > pub   4096R/6FF974DB 2019-03-01
    >   Key fingerprint = 5270 CEAC 57F6 3EBD 9EA9  005D 0253 D0B2 6FF9 74DB
    > uid                  GetEnvoy <getenvoy@tetrate.io>
    > sub   4096R/7767A960 2019-03-01

5. Add the stable repository.
    To add the nightly repository instead, replace the word stable with nightly.
    
    ```
    $ sudo add-apt-repository \
    "deb [arch=amd64] https://dl.bintray.com/tetrate/getenvoy-deb \
    $(lsb_release -cs) \
    stable"
    ```

**System Information (please complete the following information):**
 - OS: Ubuntu 20.10

**Comment by musaprg** [comment]
@tscpp Hi. As mentioned here(https://github.com/tetratelabs/getenvoy/issues/119), the envoy binaries installed with GetEnvoy only support LTS versions of Ubuntu. For now, could you try to use the build for the latest LTS version (20.04) of Ubuntu?

**Comment by tscpp** [comment]
Thank you!
