### ISSUE TITLE
Please ship the envoy "tools"

### ISSUE THREAD

**Issue by antifuchs** [tetratelabs/getenvoy-package#114]
**Is your feature request related to a problem? Please describe.**

I'm trying to upgrade a configuration file from an envoy 1.5.0 install to be compatible with version 1.13.1; of course, valid keys got renamed/deprecated/removed. My iteration time would be far faster (and my deployments far safer!) if I could use the [config load check tool](https://www.envoyproxy.io/docs/envoy/latest/install/tools/config_load_check_tool) that envoy has in its source tree - but none of the binary distributions of envoy ship it; I have to build it myself, in a process that's kinda slow.

**Describe the solution you'd like**

Please build and ship the tools, especially `config_load_check_tool` as an additional installation target, e.g. `config_load_check_tool:1.13.1/linux-glibc` similar to `standard:1.13.1/linux-glibc`.

**Describe alternatives you've considered**

Another approach would be to behave like the `rustup` program, in which users can choose "toolchains" that automatically get installed alongside each version; those are usually supporting programs or data files. I don't think the set of additional tools warrants having this complexity, especially as there is already a separate namespace that you could use for this.

**Additional context**

The way I imagine I'd use this is in a staged docker build toolchain: 
1. In the "build" container, download `getenvoy`, install the standard binary and config load check tool.
2. Copy the configuration into the build container and validate it with the tool.
3. Copy the envoy binary and config into the "final" container and deploy that.

**Comment by codefromthecrypt** [comment]
FYI I mentioned this in a discussion of upstream hosting https://github.com/envoyproxy/envoy/issues/16830

**Comment by codefromthecrypt** [comment]
we won't be producing system packages long term. please follow https://github.com/envoyproxy/envoy/issues/16867 for "official" ones
