### ISSUE TITLE
bintray deb/ubuntu repo is definitively dead (planned shutdown since Feb 2021)

### ISSUE THREAD

**Issue by SLoeuillet** [tetratelabs/getenvoy-package#122]
**Describe the bug**
bintray (used for debian/ubuntu packages at least) is closing (should have been 2021-05-01 but it seems they extended up to 2021-07-01)  :
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Any apt-get update with that repo would do :

Err:6 https://dl.bintray.com/tetrate/getenvoy-deb focal InRelease
  403  Forbidden [IP: 52.88.131.165 443]
Reading package lists... Done                   
E: Failed to fetch https://dl.bintray.com/tetrate/getenvoy-deb/dists/focal/InRelease  403  Forbidden [IP: 52.88.131.165 443]
E: The repository 'https://dl.bintray.com/tetrate/getenvoy-deb focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

(Same for both bintray IP addresses)

**To Reproduce**
1. apt-get update

**Expected behavior**
envoy packages still available

**System Information (please complete the following information):**
Ubuntu 20.04 LTS / Focal

**Comment by SLoeuillet** [comment]
Found new official repos ?
https://cloudsmith.io/~tetrate/repos/getenvoy-deb-stable/setup/#formats-deb

Anyway, debian & ubuntu install pages on envoy website still point to bintray

**Comment by SLoeuillet** [comment]
I doubt it is official / target as some latest release are missing :

  Version table:
     1.18.2.p0.gd362e79-1p75.g76c310e 500
        500 https://deb.dl.getenvoy.io/public/deb/ubuntu focal/main amd64 Packages
     1.17.1.p0.gd6a4496-1p74.gbb8060d 500
        500 https://deb.dl.getenvoy.io/public/deb/ubuntu focal/main amd64 Packages
     1.17.0.p0.g5c801b2-1p72.g28ef262 500
        500 https://deb.dl.getenvoy.io/public/deb/ubuntu focal/main amd64 Packages
     1.17.0.p0.g5c801b2-1p71.gbe6132a 500
        500 https://deb.dl.getenvoy.io/public/deb/ubuntu focal/main amd64 Packages
     1.16.2.p0.ge98e41a-1p71.gbe6132a 500
        500 https://deb.dl.getenvoy.io/public/deb/ubuntu focal/main amd64 Packages
     1.16.0.p0.g8fb3cb8-1p69.ga5345f6 500
        500 https://deb.dl.getenvoy.io/public/deb/ubuntu focal/main amd64 Packages
...

**Comment by lyrixx** [comment]
see https://github.com/envoyproxy/envoy/issues/16867#issuecomment-861658075

**Comment by codefromthecrypt** [comment]
apologies for folks who will get a boiler-plate reply, but I feel each issue deserves an answer even if they are opened redundantly:

The last published packages are in cloud smith, not bintray. Apologize but the docs are not updated yet https://github.com/envoyproxy/envoy/pull/17246

We've updated the website for options moving forward because this project is canceled due to trademark issues with The Linux Foundation https://getenvoy.io
