### ISSUE TITLE
FIPS Compliant Envoy Build for centos 7  & ubuntu

### ISSUE THREAD

**Issue by skyrocknroll** [tetratelabs/getenvoy-package#20]
**Is your feature request related to a problem? Please describe.**
FIPS Compliant Envoy Build for centos 7 

**Describe the solution you'd like**
We would like to get a build with FIPS following the build instructions mentioned 
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/ssl#fips-140-2

**Describe alternatives you've considered**
Trying to build ourself does causes a lot of frustrations

**Additional context**
Envoy FIPS compliant build for ubuntu & centos 7

**Comment by liamawhite** [comment]
cc @lizan

**Comment by lizan** [comment]
Yes this is in my scope but didn't have bandwidth to setup CI yet.

**Comment by skyrocknroll** [comment]
@lizan I saw a couple of commits related to fips. are fips packages going to be available soon?

**Comment by codefromthecrypt** [comment]
we won't be producing system packages long term. please follow https://github.com/envoyproxy/envoy/issues/16867 for "official" ones
