### ISSUE TITLE
Builds of Istio-Proxy

### ISSUE THREAD

**Issue by liamawhite** [tetratelabs/getenvoy-package#23]
The GetEnvoy CLI should be able to consume builds of Istio-Proxy. This means building and publishing it via the manifest.

Note: It is not necessary to distribute via package managers.

**Comment by liamawhite** [comment]
@lizan could you take this and give an ETA?

**Comment by lizan** [comment]
Almost done, 1.2.5 binary: https://tetrate.bintray.com/getenvoy/getenvoy-istio-proxy-1.2.5.p0.g490fa3f-1p34.g71784a0-linux-glibc-release-x86_64.tar.xz

**Comment by codefromthecrypt** [comment]
stale
