### ISSUE TITLE
Provide DEBUG binaries

### ISSUE THREAD

**Issue by javiervazquezh** [tetratelabs/getenvoy-package#24]
Hello,

Not sure if this is already available but it'd be helpful to provide DEBUG binaries as well. It could be via a different package manager repository or flag.   

Thanks,
Javier Vazquez

**Comment by liamawhite** [comment]
Could you clarify what you mean by debug binaries? Are you referring to compilation with `gperftools` for CPU/Head profiling?

**Comment by javiervazquezh** [comment]
Hi @liamawhite,

By debug binaries I mean to provide binaries with debug symbol resolution for debugging scenarios. When building Envoy on release mode you provide the flag "-c opt" and  for debug is "-c dbg".

RELEASE: bazel build -c opt //source/exe:envoy-static
DEBUG: bazel build -c dbg //source/exe:envoy-static

https://docs.bazel.build/versions/master/user-manual.html#flag--compilation_mode

Thanks,
Javier

**Comment by lizan** [comment]
`gperftools` is always built-in, if you're just looking for symbols, we do keep the release binaries with symbol before stripping in bintray to debug the core dump produced from releases. It is undocumented now though.

**Comment by javiervazquezh** [comment]
Hi @lizan ,

Yes, I'm just looking for symbols. Documenting how to get the release binaries with symbols should be enough.

Thanks,
Javier

**Comment by lizan** [comment]
@javiervazquezh OK thanks for clarification.

Meanwhile if you're looking for our current releases, you can find binaries with symbol here:
https://tetrate.bintray.com/getenvoy/
