### ISSUE TITLE
FIPS complaint binary for Debian 

### ISSUE THREAD

**Issue by AmbarSawant** [tetratelabs/getenvoy-package#64]
**Is your feature request related to a problem? Please describe.**
We have FIPS compliance requirements and hence we would like a FIPS compliant binary of Envoy

**Describe the solution you'd like**

FIPS compliant binary of Envoy or guidance on how we can build one.

**Describe alternatives you've considered**

This is a mandatory requirement.

**Additional context**

**Comment by liamawhite** [comment]
Thanks for the request, this is in the works but we don't yet have an ETA.

**Comment by codefromthecrypt** [comment]
we won't be producing system packages long term. please follow https://github.com/envoyproxy/envoy/issues/16867 for "official" ones
