### ISSUE TITLE
Is hot-restart disabled?

### ISSUE THREAD

**Issue by acrazing** [tetratelabs/getenvoy-package#65]
I cannot get any information about how to enable `hot-restart` and the log shows `hot-restart-version` is `disabled`.

start with `--hot-restart-version` will exit:

```bash
$ envoy --restart-epoch 1 -c envoy.yaml --hot-restart-version
disabled
```

start first process:

```bash
$ envoy --restart-epoch 1 -c envoy.yaml
# ...
[2019-12-25 23:29:24.983][428252][info][main] [external/envoy/source/server/server.cc:249] initializing epoch 1 (hot restart version=disabled)
# ...
```

start second process:

```bash
$ envoy --restart-epoch 1 -c envoy.yaml
# ...
cannot bind '0.0.0.0:9901': Address already in use
```

**Comment by lizan** [comment]
@acrazing Are you running on macOS? Hot restart is not supported on macOS. Please file an issue in upstream to get that supporrted.

**Comment by lizan** [comment]
On Linux I can confirm `envoy --hot-restart-version` returns `11.104`

**Comment by acrazing** [comment]
@lizan I tested it works on my CentOS 7 server, thank you very much.
