### ISSUE TITLE
Stable is missing from Ubuntu focal

### ISSUE THREAD

**Issue by kanongil** [tetratelabs/getenvoy-package#84]
**Describe the bug**

Instructions from here fail: https://www.getenvoy.io/install/envoy/ubuntu/

**To Reproduce**
1. Run `sudo add-apt-repository "deb [arch=amd64] https://dl.bintray.com/tetrate/getenvoy-deb $(lsb_release -cs) stable"`
2. Run `sudo apt-get update && sudo apt-get install -y getenvoy-envoy`
3. Error `E: Unable to locate package getenvoy-envoy`

**Expected behavior**
Succesful installation.

**System Information (please complete the following information):**
 - OS: Ubuntu 20.04 LTS (focal)
 - `lsb_release -cs`: focal

**Comment by kanongil** [comment]
This is still an issue. While it has been added in #83, I guess it won't be published until a new stable release is created? Or someone forces it through?

**Comment by own-being** [comment]
It's Same to me.

**Comment by lizan** [comment]
Yes it won't be published until a new stable release is created. Meanwhile you should be able to use what we release for `xenial` (i.e. use `sudo add-apt-repository "deb [arch=amd64] https://dl.bintray.com/tetrate/getenvoy-deb xenial stable"`, all ubuntu/debian deb package are identical.

**Comment by kanongil** [comment]
This is working now with the 1.14.2 release.

**Comment by sebolabs** [comment]
That doesn't work neither for focal nor for xenial...
```
# apt-cache policy
Package files:
[...]
 500 https://dl.bintray.com/tetrate/getenvoy-deb focal/stable amd64 Packages
     release o=Bintray,a=focal,n=focal,l=Bintray,c=stable,b=amd64
     origin dl.bintray.com
[...]

# apt list getenvoy-envoy
Listing... Done
getenvoy-envoy/focal 1.17.1.p0.gd6a4496-1p74.gbb8060d amd64

# apt install getenvoy-envoy
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package getenvoy-envoy
```

How do I get it installed on Ubuntu 20.04?
