### ISSUE TITLE
Support Amazon Linux

### ISSUE THREAD

**Issue by goedelsoup** [tetratelabs/getenvoy-package#89]
**Is your feature request related to a problem? Please describe.**
The GetEnvoy yum repo cannot be used to install envoy on Amazon Linux. The install currently fails due to a misintepretation of `relversion` leading to a path of `centos/2`.

**Describe the solution you'd like**
Extend yum repo to support installation on Amazon Linux.

**Describe alternatives you've considered**
I am currently installing directly from the GitHub releases, however, it would be preferable to maintain the installation through yum.

**Comment by codefromthecrypt** [comment]
we won't be producing system packages long term. please follow https://github.com/envoyproxy/envoy/issues/16867 for "official" ones
