### ISSUE TITLE
Bad signature for getenvoy-deb on Ubuntu Xenial as of 9 hours ago

### ISSUE THREAD

**Issue by jamiees2** [tetratelabs/getenvoy-package#93]
**Describe the bug**
When I try to `apt-get update` the getenvoy-deb repository, it fails with a bad signature error. This is on a machine that previously worked, and started happening right as the new release was pushed 9 hours ago: https://bintray.com/tetrate/getenvoy-deb/getenvoy-envoy/view/files/pool/nightly/g/getenvoy-envoy#files/dists%2Fxenial%2Fmain%2Fbinary-amd64.

This is currently blocking new machine launches for us, while old machines continue to use the pre-signature failure version.

**To Reproduce**
1. Run `apt-get update` on an Ubuntu Xenial machine

**Expected behavior**
I expected the signature to match

**System Information (please complete the following information):**
Ubuntu Xenial

**Additional context**
Relevant output from `apt-get update`
```
Ign:9 https://dl.bintray.com/tetrate/getenvoy-deb xenial InRelease
Get:10 https://dl.bintray.com/tetrate/getenvoy-deb xenial Release [16.0 kB]
Hit:10 https://dl.bintray.com/tetrate/getenvoy-deb xenial Release
Get:11 https://dl.bintray.com/tetrate/getenvoy-deb xenial Release.gpg [821 B]
Ign:11 https://dl.bintray.com/tetrate/getenvoy-deb xenial Release.gpg
Fetched 110 kB in 1s (107 kB/s)
Reading package lists...
W: GPG error: https://dl.bintray.com/tetrate/getenvoy-deb xenial Release: The following signatures were invalid: BADSIG 0253D0B26FF974DB GetEnvoy <getenvoy@tetrate.io>
W: The repository 'https://dl.bintray.com/tetrate/getenvoy-deb xenial Release' is not signed.
[2020-12-18 09:13:31.497627] [timer:stop] apt-get update (2.22 seconds)
```

**Comment by codefromthecrypt** [comment]
we won't be producing system packages long term. please follow https://github.com/envoyproxy/envoy/issues/16867 for "official" ones
