### ISSUE TITLE
debug symbols for the envoy builds that are shipped?

### ISSUE THREAD

**Issue by thomasdullien** [tetratelabs/getenvoy-package#97]
Hey there,

we are working on a continuous whole-fleet whole-system profiler; as part of this project, we are generating stack unwinds from production systems so that CPU time can be properly assigned to lines-of-code.

In one of our beta deployments, we are encountering an envoy installation that came in via getenvoy.io; we have been unable to find the debug symbols corresponding to the executable though. Is there a debug symbol repository for the executables that you shipped? If there is not, can we help change that?

Attached a screenshot from an unsymbolized flamegraph through envoy.

![Screenshot from 2021-01-28 15-29-28](https://user-images.githubusercontent.com/4587964/106152587-e3778800-617d-11eb-9e5b-248be2425954.png)

**Comment by codefromthecrypt** [comment]
FYI I mentioned this in a discussion of upstream hosting https://github.com/envoyproxy/envoy/issues/16830

**Comment by codefromthecrypt** [comment]
we won't be producing system packages long term. please follow https://github.com/envoyproxy/envoy/issues/16867 for "official" ones
